### ISSUE TITLE
DXVK-9999 build issues

### ISSUE THREAD

**Issue by SimplyCorbett** [pchome/dxvk-gentoo-overlay#8]
https://github.com/doitsujin/dxvk/issues/1067

Seems there may be some issues with this ebuild when compiling the latest dxvk master.

**Comment by pchome** [comment]
Are the latest dxvk master changes fixes the issue?

**Comment by SimplyCorbett** [comment]
Yes, e1610f8 fixed the problem.

Thank you for your fast response and everything, wasn't really expecting that from a custom overlay maintainer.
