### ISSUE TITLE
Is this overlay still being updated?

### ISSUE THREAD

**Issue by TheGreatMcPain** [pchome/dxvk-gentoo-overlay#9]
It's been a while since this overlay has been updated.

Do you still plan on maintaining it?

**Comment by pchome** [comment]
I personally use `d{9,x}vk-9999.ebuild`, so I may forgot to update versioned ones. Also, I may not have time/motivation to test versioned builds. So I recommend you to use local overlay and bump versions manually.

`/etc/portage/repos.conf/dxvk.conf`
```ini
[dxvk]
location = /path/to/repos/dxvk
sync-type = git
sync-depth = 1
sync-uri = https://github.com/pchome/dxvk-gentoo-overlay
auto-sync = true
priority = 60

[dxvk-local]
location = /path/to/repos/dxvk-local
auto-sync = false
priority = 70
```

Lower priority for local overlay - you prefer changes from dxvk overlay for two similar ebuilds.
Higher priority for local overlay - you prefer changes from your overlay for two similar ebuilds.

**Comment by TheGreatMcPain** [comment]
Okay, that makes since.

I've already been using a local overlay to bump certain things (mainly nvidia-drivers).

Thanks for for responding though.

**Comment by FireBurn** [comment]
Hi

I've been keeping an updated version of the dxvk ebuild on the FireBurn overlay

I've updated the patches for 1.3.4, I've also unslotted it, as I always want to be running the latest version without having to run the setup again

Thanks for the ebuild
